### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by owenvoke** [fervi/SteemDash#3]
I see you have a libs directory with some Composer autoloading. Is there a reason you haven't used a standard composer.json with a vendor directory?

I know that some of the files in the libs dir are css, but it may be recommended to change to a secure structure with a public directory for assets and the like.

Just a thought.

**Comment by fervi** [comment]
Just I don't like it. But if it works, I can merge to master (but I need to do some tests)

**Comment by owenvoke** [comment]
Not a problem. Just was confused as to why you'd manually include Composer packages.
